export const MEXICAN_STATES = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Estado de México",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
] as const;

export type MexicanState = (typeof MEXICAN_STATES)[number];

export const STATE_CODES: Record<MexicanState, string> = {
  Aguascalientes: "AGS",
  "Baja California": "BC",
  "Baja California Sur": "BCS",
  Campeche: "CAM",
  Chiapas: "CHIS",
  Chihuahua: "CHIH",
  "Ciudad de México": "CDMX",
  Coahuila: "COAH",
  Colima: "COL",
  Durango: "DGO",
  "Estado de México": "MEX",
  Guanajuato: "GTO",
  Guerrero: "GRO",
  Hidalgo: "HGO",
  Jalisco: "JAL",
  Michoacán: "MICH",
  Morelos: "MOR",
  Nayarit: "NAY",
  "Nuevo León": "NL",
  Oaxaca: "OAX",
  Puebla: "PUE",
  Querétaro: "QRO",
  "Quintana Roo": "QROO",
  "San Luis Potosí": "SLP",
  Sinaloa: "SIN",
  Sonora: "SON",
  Tabasco: "TAB",
  Tamaulipas: "TAMPS",
  Tlaxcala: "TLAX",
  Veracruz: "VER",
  Yucatán: "YUC",
  Zacatecas: "ZAC",
};

export const MAJOR_CITIES = {
  "Ciudad de México": { lat: 19.4326, lng: -99.1332 },
  Guadalajara: { lat: 20.6597, lng: -103.3496 },
  Monterrey: { lat: 25.6866, lng: -100.3161 },
  Puebla: { lat: 19.0414, lng: -98.2063 },
  Tijuana: { lat: 32.5149, lng: -117.0382 },
  León: { lat: 21.1221, lng: -101.6827 },
  Juárez: { lat: 31.6904, lng: -106.4245 },
  Zapopan: { lat: 20.7153, lng: -103.4029 },
  Toluca: { lat: 19.2826, lng: -99.6557 },
  Cancún: { lat: 21.1619, lng: -86.8515 },
};

export const DEFAULT_SEARCH_RADIUS_KM = 5;
export const MAX_SEARCH_RADIUS_KM = 50;
