name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/shared/**"
      - ".github/workflows/deploy-frontend.yml"

env:
  NODE_VERSION: "20"

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          cd apps/web
          npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENVIRONMENT: production

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
          vercel-args: "--prod"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get deployment URL
        id: deployment
        run: echo "url=${{ steps.vercel.outputs.preview-url }}" >> $GITHUB_OUTPUT

      - name: Run smoke tests
        run: |
          npx playwright test tests/e2e/smoke.spec.ts --project=chromium
        env:
          BASE_URL: ${{ steps.deployment.outputs.url }}

      - name: Comment deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Frontend deployed to: ${{ steps.deployment.outputs.url }}'
            })
